[versions]
agp = "8.8.2"
hiddenapibypass = "6.1"

[libraries]
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenapibypass" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
