-dontobfuscate
-dontwarn *
-keep class es.bradford1040.playintegrityfix.EntryPoint {public <methods>;}
-keep class es.bradford1040.playintegrityfix.CustomKeyStoreSpi
-keep class es.bradford1040.playintegrityfix.CustomProvider
-keep class es.bradford1040.playintegrityfix.CustomPackageInfoCreator
-keep class org.lsposed.hiddenapibypass.** { *; }
